[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator = "GocTGUf6mfZk7kqYjUyhqaGdcS5PWuJh2BnzDebwk7ih"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "emil.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
